### ISSUE TITLE
Dynamic termlists - arthropods should not be pre-populated with "not recorded"

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1039]
For arthropods, we ideally want the user to make a positive choice about the stage they are recording (even if they end up choosing "not recorded"). If we leave "not recorded" as the default, we will continue to receive a high proportion of records with stage not recorded, which is one of the issues we have been trying to resolve.

(This is less of an issue for non-arthropod taxa, where flight periods and identification features do not vary so much (arguably) between adults and early stages.)

Alongside this, we need to enable the choice made for the stage on the first row of the "enter a list" table to auto-fill for the subsequent row, unless the subsequent row contains a species from a different taxon group. At the moment, if I am entering a list of moths I have to choose "adult" for every individual entry in the list.

**Comment by kitenetter** [comment]
I see this as a priority, so am adding to the milestone. If entering long lists of species it requires many more clicks to add the stage term than used to be the case, and I fear this will lead to yet more records where people just leave the default "not recorded" stage.

**Comment by johnvanbreda** [comment]
This should be fixed now @kitenetter .

**Comment by kitenetter** [comment]
That is much improved @johnvanbreda - thanks. But it is still not quite what I saw as the ideal, sorry!

At the moment, the behaviour for invertebrates is what I hoped for: you have to make a deliberate choice of stage, which then autofills the subsequent rows unless you enter a non-invertebrate.

However, if you choose a plant or other non-invertebrate you also have to make a deliberate choice of stage, and what I was hoping for was that for non-invertebrates the stage would be pre-populated with "not recorded".

The main reason for this is that for most plant recorders "not recorded" is the correct option for most records (or so I've been told), and that we should make it easy for that to happen, while for invertebrates we really do want the recorder to tell us what stage they were recording.

If making this happen is excessively complex then we will have to stick with what we've got (which is much improved on what we had before in my opinion). A plant recorder would only have to choose "not recorded" one at the top of their list, so it is not a very onerous change. If there isn't a straightforward solution we can close the issue.

**Comment by johnvanbreda** [comment]
@kitenetter I'm not sure I agree. If you enter a list of just plants, then the default is indeed not recorded. If you enter a few taxa from a different group, e.g. arthropods, then it will clear the stage for a subsequent plant, which makes it clear to the user that the behaviour where it copies the stage from the row above can't work due to the species group change. Otherwise they might miss the fact that the copying of the value above didn't work.

**Comment by kitenetter** [comment]
Ah, I hadn't realised that if you started with a plant the default is "not recorded" - that is excellent! So I think this is now working as well as possible, which is great. Closing.
