### ISSUE TITLE
Are we sending verifier notifications for iNat records?

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#1233]
I thought we were sending out separate notifications of "records to verify" for the iRecord page and the iNat page, e.g. see #1194 

However, I can't find any recent examples of the iNat notifications being sent.

Are they still being triggered as expected?

**Comment by kitenetter** [comment]
This is my latest notification email:

![image](https://user-images.githubusercontent.com/16039111/148586554-afd1f312-aac2-4963-b020-ad2b99dcab0b.png)

Both links go to the [main verification page](https://irecord.org.uk/verification) - should one of them point to the iNat page?

**Comment by johnvanbreda** [comment]
Fixed - the active notification for one verification page was blocking sending a notification for the other page. Now the check filters the notifications on the link URL. I also updated the link so it clearly states which verification page it is for.

**Comment by DavidHepper** [comment]
Thank you @johnvanbreda - a big improvement. While on the subject, I'm still receiving empty notifications on most days.

**Comment by johnvanbreda** [comment]
@DavidHepper do you mean that the link provided takes you to the verification page but their are no records or is the email sent even though there are no notifications? If it's the former, then did you check both versions of the verification page in case it was triggered by iNat records?

**Comment by kitenetter** [comment]
Thanks for this John. I'm seeing multiple links in my emails, which seems to be unnecessary?:

![image](https://user-images.githubusercontent.com/16039111/148813973-e0eb0e78-0fb9-40cf-9880-dee4a38b716e.png)

**Comment by kitenetter** [comment]
This is about half of my latest notification for records to verify - seems a bit excessive!:

![image](https://user-images.githubusercontent.com/16039111/149026598-f6720066-c587-4b1c-b368-6b83f072a01e.png)

**Comment by johnvanbreda** [comment]
Fixed a problem in the SQL that detected existing notifications so should now be OK.
