### ISSUE TITLE
Filter by grid ref is unreliable in Explore

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#1529]
Basic filtering using 'Create a filter' seems not to work correctly today:
- Create a filter
- Define **What** = 'Insect - Dragonfly (Odonata)'
- Define **Where** = Find records in map reference > 'TQ05' and 'British National Grid'. Click **Apply**
This might work first time or it might be necessary to click **Apply** a second time.
2,154 hits are shown. Spots appear in the correct place on the map. So far, so good.

- Refine the **Where** map ref to 'TQ0050' and click **Apply**
Neither spots nor grid update, even if this is done more than once. 2,154 hits are still shown including ID 31605913 that should be shown and 31269509 with grid ref TQ06375206 that should not.

- Change the **Where** map ref again to 'TQ0652' (to include the second record above but not the first) and click **Apply**
Again, no change of grid or map after the rotating pearls finish.

**Comment by DavidHepper** [comment]
See also #1561 re. Verify

**Comment by DavidHepper** [comment]
*** Filter by Where: Grid ref it totally broken today. Filtering on grid square 'SK15' shows all records. Fixing this is urgent, please.

**Comment by kitenetter** [comment]
Not sure if this is related to the current code changes @johnvanbreda

**Comment by johnvanbreda** [comment]
Lots of updates were applied yesterday so it is likely to be related. I will look into it now.

**Comment by johnvanbreda** [comment]
@BirenRathod I think the change to headers on the warehouse1 server is preventing some cross origin requests using JSONP, which includes requests to fetch the geometry for a grid reference. If you go to https://irecord.org.uk/enter-casual-record and type in a grid reference in the "Enter a spatial reference" box (e.g. SY99) then press tab, it will send a network request which does not get a response. Please can you look into this?

**Comment by BirenRathod** [comment]
@johnvanbreda I have implemented that header but check if you find any other problem.

**Comment by johnvanbreda** [comment]
Hi @BirenRathod it is still not working. The following example link works when loaded in a browser, but when loaded from JavaScript on iRecord the content in the response is blocked:
https://warehouse1.indicia.org.uk/index.php/services/spatial/sref_to_wkt?callback=jQuery36309549124906927013_1695299068920&sref=SY92&system=OSGB&mapsystem=27700&_=1695299068921

I'm pretty sure this is a new problem since the headers were added.

**Comment by BirenRathod** [comment]
@johnvanbreda Can you check again, please? it should be fine by now.

**Comment by johnvanbreda** [comment]
No luck I am afraid. You can test it yourself though - on the casual record form on iRecord, just enter any valid spatial reference and press the tab key:
![image](https://github.com/BiologicalRecordsCentre/iRecord/assets/2392594/6c7143e2-ade2-47b1-9d11-bed70b8e47a7)

The map should move to the grid reference and draw the square, but it doesn't. If you look at the network tab you will see a request similar to the one I pasted above which has nothing on the response tab, but if you copy the request to a new browser tab's address bar then the content loads, which normally means the issue is CORS related.

**Comment by BirenRathod** [comment]
@johnvanbreda please clear the cache. it works on my machine.

**Comment by BirenRathod** [comment]
@johnvanbreda After adding grid ref, the browser asks permission to access the location. once I click yes it does show square on the map.

**Comment by johnvanbreda** [comment]
@DavidHepper or @kitenetter can you check the grid ref filter is working again please?

**Comment by BirenRathod** [comment]
> @BirenRathod it wasn't working for me, but has just started working again a minute or so ago (13:49).

@johnvanbreda It was working before but it has added one more security level which I mentioned about asking permission for location.

**Comment by BirenRathod** [comment]
@johnvanbreda The response you mentioned above is still show related to CORS.

**Comment by kitenetter** [comment]
@johnvanbreda @DavidHepper for me the grid square filter is now working again on the Explore all records page.

**Comment by johnvanbreda** [comment]
@BirenRathod I think the asking for location permission is a "red herring", i.e. not relevant, since we only ask permission to get your location when you click the circle target button. This problem was a request to convert a typed in grid reference to a geometry via a web-service and it didn't need to relate to your current location. I tested on another Indicia site which also had the same problem 30 minutes ago and it has now started working, but I definitely have not given the browser permission to ask for my location, so something else changed which fixed it.

**Comment by BirenRathod** [comment]
@johnvanbreda you can test here -> https://dev-brc-test-irecord.pantheonsite.io/enter-casual-record
Once you give the permission, it doesn't stop you from getting that location on the map.

**Comment by BirenRathod** [comment]
@johnvanbreda The difference is that you need to click on the location icon instead of using the tab. Tab will not work unless you change the even trigger code in javascript.

**Comment by johnvanbreda** [comment]
There is an event handler on the change event of the spatial reference input control which triggers the network request to convert the typed-in grid reference into a geometry to draw on the map. This is a separate function to the "Find my current location" target button, which requests the current location from the browser then fills in the grid ref and draws it on the map. That button of course only works if you give permission, but if you change the spatial reference value manually then when you leave the control (e.g. press tab, or click on the next control), it sends the network request to the warehouse. This is now working on warehouse 1 but as far as I can see it is failing still on the dev warehouse.

**Comment by BirenRathod** [comment]
yes, @johnvanbreda it is failing and that is my point. it is failing because of the added security level using headers. It is a mandatory requirement and we need to find a solution.

**Comment by BirenRathod** [comment]
@johnvanbreda I see below message in dev tools.
The resource from “https://devwarehouse.indicia.org.uk/index.php/services/spatial/sref_to_wkt?callback=jQuery36304243593241987279_1695304062102&sref=SY98&system=OSGB&mapsystem=3857&_=1695304062103” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

That means the code needs this <script type="text/javascript">. or content_type: text/html. 

If you haven't added it before, please add it.

**Comment by johnvanbreda** [comment]
@BirenRathod thanks - that's useful. I've hotfixed to add the correct content type headers for JSONP. I have upgraded the live warehouse but not the dev warehouse as it would overwrite some of the test code @JimBacon was working on in relation to the new triggers.

**Comment by BirenRathod** [comment]
@johnvanbreda I need those changes on the dev warehouse, so I can test it before making changes on the live warehouse. Is it possible?

**Comment by JimBacon** [comment]
Don't worry about over-writing my code on the dev warehouse. However, I am worried that John may have broken the apps with his change. Something is wrong.

**Comment by BirenRathod** [comment]
@johnvanbreda Are you making changes on devwarehouse, so I can test?

**Comment by johnvanbreda** [comment]
I've applied the latest code to the devwarehouse now, though it may also include Jim's broken change in 8.23.2.

**Comment by JimBacon** [comment]
It does include it but it may be the test that is broken rather than the code change since my manual tests worked as expected.

**Comment by kitenetter** [comment]
@JimBacon we are getting reports that the PoMS FIT Count app is failing to upload records (error "Sorry, Load Failed") - is this likely to be related to the above?

**Comment by JimBacon** [comment]
@kitenetter All the apps stopped uploading. We have removed all the changes made to the live server today and iRecord and Butterfly Count started working again.

**Comment by BirenRathod** [comment]
Thanks, @johnvanbreda. I'm not worried about those broken changes. it should not stop testing my work.
@johnvanbreda Good news. that works fine. So that left to resolve the app problem. 
 
you can test here https://dev-brc-test-irecord.pantheonsite.io/enter-casual-record.

**Comment by johnvanbreda** [comment]
@JimBacon 

> It does include it but it may be the test that is broken rather than the code change since my manual tests worked as expected.

The test that fails is posting an occurrence into a sample via REST, then checking that the ID of the occurrence indicated by the response actually exists. It is failing to find the occurrence probably because the ID in the response is wrong, potentially as a result of the triggers. So I think the test is correctly failing because the response from the POST is wrong, not because the data fails to post. 

The REST api does use the standard ORM objects when saving data so I would have expected any fix to work though.

**Comment by JimBacon** [comment]
I've run out of time for now. The database update seems to apply fine. I've just developped a hunch which is that I fixed the occurrence data model but possibly the sample data model needs the same fix. I'll return to this on Monday but feel free to take over if it is urgent.

**Comment by JimBacon** [comment]
I've switched my working days to continue with this as I remembered the [training record issue](https://github.com/Indicia-Team/warehouse/issues/493) is still present and it causes scheduled tasks to break.

**Comment by johnvanbreda** [comment]
@JimBacon I'm trying to review the triggers to see if they are really necessary and noticed that the sample table trigger would only fire if the training flag on the sample is set from false to true. I don't think the test does that, so presumably fixing the sample table in the way you've already fixed the occurrences table will not fix the test.

Also I note that there are other tests in the dataTest class which I am very surprised did not pick up the change of functionality we believe the triggers have caused before you applied your fix.

**Comment by johnvanbreda** [comment]
Ignore this comment:

> Also I note that there are other tests in the dataTest class which I am very surprised did not pick up the change of functionality we believe the triggers have caused before you applied your fix.

The tests don't pick up the problem because they are not using training mode. I'll add a test for this scenario.

**Comment by JimBacon** [comment]
The test is failing at line 522 of /modules/rest_api/tests/Rest_ControllerTest.php 
`$allMatch = $storedItem['values']['id'] === $id;`

$storedItem is an occurrence and $storedItem['values']['id'] is a string.
$id is an integer so the equality is never satisfied and the test cannot pass.

I'm wondering why this is only now appearing as a problem.

**Comment by johnvanbreda** [comment]
The $hasTriggerWithSequence flag causes the ORM object's ID to be overwritten with a new value which is an integer. The value it replaces was a string representation of the same integer. The test uses a === check when searching for the record of a known posted ID. Hence it fails if $hasTriggerWithSequence is true. Although this seems like a test case issue rather than a real problem, the change of the ID from a string to an integer might have other impacts that it would be difficult to predict.

**Comment by johnvanbreda** [comment]
Closing as the initial issue is now sorted and the latter issue related to test cases is also sorted.

**Comment by JimBacon** [comment]
For future reference, the final comments above related to the issues https://github.com/Indicia-Team/warehouse/issues/493 and https://github.com/BiologicalRecordsCentre/ABLE/issues/626
