### ISSUE TITLE
Explore & Verify: input is not sanitised

### ISSUE THREAD

**Issue by DavidHepper** [BiologicalRecordsCentre/iRecord#160]
Some iRecord fields are not sanitised / validated as well as they could be on the client (?or server) side before being submitted. Mundanely, invalid input can be hard to spot and it triggers generic errors such as "The report did not load correctly." that give no clue as to the reason. It might even enable SQL injection attacks. 

_Example:_ Enter (or paste) a number with one or more trailing space characters into the ID entry field of **Create Filter > Record ID**.

**Comment by johnvanbreda** [comment]
This isn't actually a sanitisation problem - rather it is a poor handling of the error response given by the warehouse when the parameter isn't valid. I've fixed it in the development branch so it will be released at the next feature release.

**Comment by kitenetter** [comment]
@johnvanbreda can we close this?

**Comment by DavidHepper** [comment]
Sorry, I didn't mean to close this one. It isn't fixed, even if it's explained. Could the input be Trimmed, at least? It is very easy to pick up a trailing space when copying a Record ID - from the grid, perhaps.
