### ISSUE TITLE
Timeout errors for verification filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#470]
Currently experiencing problems when trying to set up verification filters. When I try to add vice-counties to the "Where" part of the filter I'm getting a timeout error - the message doesn't allow the error text to be copied but it starts off as:

![image](https://user-images.githubusercontent.com/16039111/50963131-c05cdb80-14c3-11e9-89d7-50c7f06cbf19.png)

The system seems generally slow this morning so perhaps there are other procedures being run that are causing temporary glitches?

**Comment by BirenRathod** [comment]
@kitenetter 

Is it possible to send me the SQL  query which you mentioned above.

**Comment by kitenetter** [comment]
I have now managed to reproduce it - I did so by setting up a new filter with two vice-counties selected (which worked fine), and then going back in to the "Where" setting to remove one of the vice-counties (which produced the error). The first part of the error message is as shown above, the second part is:

![image](https://user-images.githubusercontent.com/16039111/50965828-0d907b80-14cb-11e9-99c8-dcefe519ca83.png)

and the third part is:

![image](https://user-images.githubusercontent.com/16039111/50965861-2731c300-14cb-11e9-9d24-9e18c72d98f9.png)

**Comment by kitenetter** [comment]
If I close the error message box it seems that I can then continue to edit the filter and it saves okay, so this isn't causing any significant problems as far as I can see - feel free to close this issue unless you think there is something we ought to investigate.

**Comment by kitenetter** [comment]
Possibly related: sometimes the verification filter settings are not allowing me to add more than one parameter, e.g. I'm trying to set up a filter for beetles and true bugs - it took several minutes to find the entry for beetles, and now is not displaying anything when I try to add a second taxon group:

![image](https://user-images.githubusercontent.com/16039111/50966330-8512da80-14cc-11e9-96ee-a8365d9b4d7b.png)

**Comment by BirenRathod** [comment]
@kitenetter 
The query in where is still not complete. Is it possible to paste whole query here please?

**Comment by kitenetter** [comment]
No it isn't, all I can see is what is shown in the screenshots above, it doesn't allow me to copy the text itself, and I can't find any way of expanding the view.

**Comment by BirenRathod** [comment]
@kitenetter 
The timeout error occurred due to bug in SQL statement.
I think John needs to look at it first. Is it possible to send me the steps to reproduce?

**Comment by BirenRathod** [comment]
@kitenetter 
Yes, I guessed correctly. One of the SQL didn't find the column when click on Map tab. Certainly John to investigate about it.

**Comment by johnvanbreda** [comment]
Actually, I think all these timeout errors were because of the server upgrade having not enough processor cores. I can't reproduce any of the issues now that the processor has been corrected. Please re-open if I am wrong.

**Comment by kitenetter** [comment]
I'm still getting these error messages nearly every time I edit or create a verification filter. If I ignore the error message the filters do seem to be saving correctly (as far as I can tell).

**Comment by johnvanbreda** [comment]
Ok, the problem I've found is that this page opens with an unfiltered view (sharing mode=reporting). The page issues a query to grab the first page of records, plus a 2nd query to count them for the pager. Then you switch to verification mode so the queries are re-issues, including a 2nd unfiltered count query. Although the ajax request is stopped for the first count, PostgreSQL doesn't abort the query (there is no easy way to do this) so it continues trying to count 2 unfiltered datasets, hence the timeout messages which eventually appear. It's horrendous for performance and I noticed this affecting general server performance (though hadn't realise where all the unfiltered count queries were coming from!) so I've removed the pager from this page - the benefits are far outweighed by the costs in this case. Hope that's OK.

**Comment by kitenetter** [comment]
@johnvanbreda I'm still seeing these timeout error messages when I create new filters, although as before they don't seem to be preventing the filter being saved correctly (as far as I can tell). Do we need to re-open this one?

**Comment by kitenetter** [comment]
Now seeing timeout errors repeatedly and have been unable to create a filter for PoMS data (which needs to include unreleased records):

![image](https://user-images.githubusercontent.com/16039111/53373309-f9a2bb00-394c-11e9-971e-89d38575b30d.png)
