### ISSUE TITLE
Zooming into area in Northern Ireland leads to blank basemap

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/iRecord#601]
When zoomed in to an area in Northern Ireland beyond a certain point using the dynamic layer, the OS layer kicks in – taking over from OSM. NI is within the bounding rectangle where they dynamic layer serves the OS Leisure map by preference. However, the OS map for NI is blank so it looks like the layers have disappeared.

**Comment by burkmarr** [comment]
Pull request with a fix for this: https://github.com/Indicia-Team/media/pull/16

**Comment by burkmarr** [comment]
@kitenetter - this is fixed in develop now - see here : http://test.brc.ac.uk/irecord_dev/enter-casual-record. I'm a little confused however since it no longer appears to be a problem on the live site. Did you move a fix into the live site independent of this @johnvanbreda? What is still evident on the live site is the problem of not getting to OS when zooming in on the tip of the Kintyre penninsula (referred to here: https://github.com/Indicia-Team/media/pull/16), but this is fixed on irecord_dev.

**Comment by johnvanbreda** [comment]
@burkmarr No, other than the fixes we've discussed I've not fixed the live site, though I can actually still see this problem on the casual record form.

**Comment by burkmarr** [comment]
@johnvanbreda - so can I now! I can only assume that although I thought that I was looking at the live site, I must have been looking at irecord_dev.

**Comment by burkmarr** [comment]
Merged to master. https://github.com/Indicia-Team/media/commit/4c46fb9ff4060074db1b25059b023e1c9f908830
