### ISSUE TITLE
Ordering of species within drop-down menu

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/iRecord#669]
At the moment the ordering is not sensible. Hybrids frequently appear before a species, leading to data entry errors. For example, Rumex obtusifolius appears 9th in the list after 8 other hybrids, even after typing the full name. Martin Harvey and I are in agreement that some sort of weighting would be desirable, such that species always appear before hybrids, genera and infraspecific taxa.

(Assigning to @burkmarr marr as @kitenetter said that he was working on UKSI issues)

**Comment by DavidRoy** [comment]
liked to #636 
@burkmarr can you review this as an option linked to the UKSI update scheduled for September?

**Comment by sacrevert** [comment]
Thanks @DavidRoy @burkmarr 
I am convinced that this is currently the biggest problem for data quality within the NPMS. I've just spent 2 days going through the data making corrections, a large proportion of which are caused by this issue. Similarly there are issues with genus-level data as well, where people search for a common name (e.g. Agrimony), and then select the first hit in the dropdown, which in this case is the genus. I'm looking at other nudges to avoid this behaviour, but sorting out this dropdown ordering would be a huge help!

**Comment by burkmarr** [comment]
Turns out a major part of this is due to a bug - i.e. it's not currently working as designed. It looks like a good deal of thought has gone into the sort order, but it's using some regular expressions which are case sensitive and not working. Perhaps they did work with an earlier version of Postgres.

The file is warehouse\application\helpers\postgreSQL.php and the lines in question are these:

```sql
-- prefer matches with searched phrase near start of term, by discarding the characters from the search term onwards and counting the rest
length(regexp_replace(searchterm, replace('$escapedTerm', ' ', '.*') || '.*', '','i')),
-- prefer matches where the full search term is close together, by counting the characters in the area covered by the search term
case
  when searchterm ilike '%' || replace('$escapedTerm', ' ', '%') || '%'
    then length(searchterm) - length(regexp_replace(searchterm, replace('$escapedTerm', ' ', '.*?'), ''))
  else 9999 end,
cts.preferred desc,
```
The 'searchterm' in the query is the column in the cache_taxon_searchterms table that is searched against ($escapedTearm is derived from the user's search term). In the modified version below, 'searchterm' is replaced with 'lower(searchterm)' where it is used in regular expressions (twice).
```sql
-- prefer matches with searched phrase near start of term, by discarding the characters from the search term onwards and counting the rest
length(regexp_replace(lower(searchterm), replace('$escapedTerm', ' ', '.*') || '.*', '','i')),
-- prefer matches where the full search term is close together, by counting the characters in the area covered by the search term
case
  when searchterm ilike '%' || replace('$escapedTerm', ' ', '%') || '%'
    then length(searchterm) - length(regexp_replace(lower(searchterm), replace('$escapedTerm', ' ', '.*?'), ''))
  else 9999 end,
cts.preferred desc,
```
With that fixed, a search against 'Rumex obtusifolius' which is currently producing this...
```
Rumex aquaticus x obtusifolius = R. x platyphyllus
Rumex confertus x obtusifolius = R. x borbasii
Rumex conglomeratus x obtusifolius = R. x abortivus
Rumex crispus x obtusifolius = R. x pratensis
Rumex cristatus x obtusifolius = R. x lousleyi
Rumex frutescens x obtusifolius = R. x cornubiensis
Rumex hydrolapathum x obtusifolius = R. x weberi
Rumex longifolius x obtusifolius = R. x hybridus
Rumex obtusifolius
Rumex obtusifolius var. microcarpus
Rumex obtusifolius var. obtusifolius
Rumex obtusifolius x maritimus = R. x callianthemus
Rumex obtusifolius x palustris = R. x steinii
Rumex obtusifolius x rupestris
Rumex patientia x obtusifolius = R. x erubescens
Rumex pulcher x obtusifolius = R. x ogulinensis
Rumex sanguineus x obtusifolius = R. x dufftii
Rumex aquaticus x obtusifolius
Rumex aquaticus x obtusifolius (R. x platyphyllos)
Rumex confertus x obtusifolius
Rumex confertus x obtusifolius (R. x borbasii)
```
would produce this...
```
Rumex obtusifolius
Rumex obtusifolius var. microcarpus
Rumex obtusifolius var. obtusifolius
Rumex obtusifolius x maritimus = R. x callianthemus
Rumex obtusifolius x palustris = R. x steinii
Rumex obtusifolius x rupestris
Rumex obtusifolius subsp. sylvestris
Rumex obtusifolius subsp. sylvestris
Rumex obtusifolius subsp. transiens
Rumex obtusifolius subsp. transiens
Rumex obtusifolius var. transiens
Rumex obtusifolius var. transiens
Rumex obtusifolius var. transiens
Rumex obtusifolius x palustris
Rumex obtusifolius x palustris (R. x steinii)
Rumex obtusifolius x patientia
Rumex obtusifolius x patientia (R. x erubescens)
Rumex obtusifolius x pulcher
Rumex obtusifolius x pulcher (R. x ogulinensis)
Rumex obtusifolius x sanguineus
Rumex obtusifolius x sanguineus (R. x dufftii)
```
The query is only bringing back the first 21 matches after sorting which accounts for why the two lists contain different taxa.

Although this is not perfect - for example you might want all varieties to be shown before subspecies, or visa versa - it is a massive improvement and addresses all your original concerns bar one which is that 

> species always appear before [...] genera.

Here's a search on 'Rumex' with the bug fixed...
```
Rumex
Rumex acetosa
Rumex acetosa subsp. acetosa
Rumex acetosa subsp. ambiguus
Rumex acetosa subsp. biformis
Rumex acetosa subsp. celticus
Rumex acetosa subsp. hibernicus
Rumex acetosella
Rumex acetosella subsp. acetosella
Rumex acetosella subsp. pyrenaicus
Rumex alpinus
Rumex altissimus
Rumex aquaticus
Rumex aquaticus x crispus = R. x conspersus
Rumex aquaticus x obtusifolius = R. x platyphyllus
Rumex aquaticus x sanguineus = R. x dumulosus
Rumex bequaertii
Rumex brownii
Rumex bucephalophorus
Rumex confertus
Rumex confertus x crispus = R. x skofitzii
```
Personally I'd rather the genus *did* come before species because if I only want to record something to genus, I shouldn't have to scroll down a long list to find it. Also, in this case, it matches my search criteria exactly and surely should be the top result?

Anyway, clearly that kind of nuance is open to discussion and what is best for one person might not be best for another. But fixing this bug is probably best for everyone. So I would suggest that we get this bug fixed ASAP, and worry about the nuances later? What do you think?

**Comment by kitenetter** [comment]
@burkmarr I would support fixing the bug and then reviewing the nuances.

Will this also change the behaviour when entering via vernacular names. For example, at the moment if you type in the moth Ruby Tiger you get offered a subspecies first, and I think it should be binomial first:

![image](https://user-images.githubusercontent.com/16039111/64181933-423cb300-ce5f-11e9-8aa3-96270b4fb8fe.png)

**Comment by burkmarr** [comment]
Apparently yes! (I wish I could say that I knew it would before I tried it!)
![image](https://user-images.githubusercontent.com/9275178/64182545-4cab7c80-ce60-11e9-8e2e-9a1b110c56a7.png)

**Comment by japonicus** [comment]
@burkmarr the first regular expression already has the case insensitive 'i' flag, so lower() shouldn't be needed. 'i' is missing from the second test, possibly adding it would solve the problem slightly more efficiently than using lower(). e.g.

```sql
-- prefer matches with searched phrase near start of term, by discarding the characters from the search term onwards and counting the rest
length(regexp_replace(searchterm, replace('$escapedTerm', ' ', '.*') || '.*', '','i')),
-- prefer matches where the full search term is close together, by counting the characters in the area covered by the search term
case
  when searchterm ilike '%' || replace('$escapedTerm', ' ', '%') || '%'
    then length(searchterm) - length(regexp_replace(searchterm, replace('$escapedTerm', ' ', '.*?'), '', 'i'))
  else 9999 end,
cts.preferred desc,
```

**Comment by burkmarr** [comment]
Good shout @japonicus - I'll give it a go.

**Comment by burkmarr** [comment]
That worked @japonicus. I guess it was there originally and went AWOL somewhere along the way. I agree it's better than using lower().

**Comment by sacrevert** [comment]
Thanks @burkmarr 
With respect to the genus level issue, in the context of the NPMS, this was mainly a concern when searching common names, not when searching the scientific name. I agree that 'Rumex' is the best top hit when searching the genus only.

**Comment by johnvanbreda** [comment]
@burkmarr shall I hotfix this using @japonicus' solution?

**Comment by burkmarr** [comment]
That would be great @johnvanbreda.

**Comment by johnvanbreda** [comment]
Done. Thanks @burkmarr and @japonicus.

**Comment by burkmarr** [comment]
Looks like the Ruby Tiger problem is still there @kitenetter . Probably just coincidence that I didn't see it on my local setup (I have a different version of the UKSI). It's one that we should revisit in the context of a wider discussion about search list ordering and produce a new issue off the back of that.

**Comment by johnvanbreda** [comment]
@burkmar the trick here will be to use cts.taxon_rank_sort_order to inject some notion of preference for species level taxa into the sort order. Currently because the sort order is based on the searched name and Ruby Tiger appears twice, the order is indeterminate which may be why you thought it was OK. If you add the following to the sort order (perhaps just before the final alpha sort) then it works better:
```
abs(cts.taxon_rank_sort_order - 300),
```
This takes the "distance" from 300 (the sort order of the species rank) into account so the further down or up the tree the later in the order. This is just an experiment, you might come up with something better. Also note that the value 300 comes from UKSI but is not hard coded in Indicia so might need to be configurable.

**Comment by burkmarr** [comment]
Thanks John that's useful and would sort out the Ruby Tiger issue. I can't spot any down-sides to it as long as it comes down the order of precedence as you've suggested. 

I think that we need to take a hollistic view to this before doing much work on it because there is a danger that fixing problems for one use case could just create problems in others. Now that the bug is fixed - which I hope should make a big difference to the data problems that @sacrevert was seeing - perhaps @sacrevert and @kitenetter could spend a few weeks or months just noting down any current problem use cases (e.g. the Ruby Tiger and the Agrimony use cases). When we have a prioritised list or problems we could then review them in the round and decide on an approach.

**Comment by japonicus** [comment]
An example of problems probably caused by species-before-genus with vernacular name results:

A search for 'clover' gives _Trifolium constantinopolitanum_ as the first suggestion. There are currently around 92 records of this, which are almost certainly wrong and intended to refer to _Trifolium_ (at genus level). (part of the solution would be to mark many ambiguous vernacular names as not-for-data-entry)

**Comment by sacrevert** [comment]
Despite my comments re Agrimony above, I can see that a general rule that the genus is listed first for ambiguous common names would be sensible, either that or a listing ordered by number of squares at some resolution in some time period (this could be at VC or country level perhaps)?

**Comment by kitenetter** [comment]
Moving this conversation to #760
