### ISSUE TITLE
Elasticsearch verification page - final tweaks

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#685]
Last few questions and requests following the implementation of the redet button and other excellent features at 3 Oct 2019.

1. Bulk verification
Within the controls shown below, does “all” mean the entire grid, and if there are filters on the grid will “all” just apply verification to the records currently displaying in the grid, across all pages?

![image](https://user-images.githubusercontent.com/16039111/66163457-4d365f00-e628-11e9-8a50-b5b7302a5768.png)

Can we add the Help text to make this clearer (and can I edit the Help text)?

2. Can we have a more meaningful icon for “Correct”?  

![image](https://user-images.githubusercontent.com/16039111/66163552-8078ee00-e628-11e9-8f2d-e4c755d0d15b.png)

3. On the verification map, do the maps for the currently selected species only show verified records, or verified + unreviewed? (Presumably rejected are not shown?)

4. Performance is variable for individual record verification: first three verifications processed almost instantly, fourth took 35 seconds to process, for no apparent reason. We can live with this but it does make it difficult to maintain a flow when trying to work through large sets of records.

**Comment by kitenetter** [comment]
1. The recently added Redet button works, but the taxon displayed in the grid for the redetermined record is not immediately refreshed, and thus at first glance it appears the redet has not worked (although the comments tab does update immediately to show that it does work). 

Are we able to force an immediate refresh in the grid following a redet? If not we will need to explain the delay clearly in our documentation (and perhaps add a Help button somewhere near the redet button).

2. If I set my grid filter to show "all records", and I then verify a previously unverified record, that record gets taken out of the grid. Ideally it should remain visible since the filter should be including all records.

**Comment by kitenetter** [comment]
I thought this had been raised before but I can't find it (and let me know if this needs to be a separate issue): having used the 'grid column settings' tool to specify the columns that I wish to see in my grid, it would be really helpful to be able to save those settings, rather than having to recreate them every time. (And in an absolutely ideal world it would be nice to be able to save more than one set of column settings, i.e. to have a number of templates that one could apply.)

The grid column settings tool is hugely useful!

**Comment by johnvanbreda** [comment]
@kitenetter the last used settings should be saved in a cookie and reloaded. Is this not happening for you? If not can I have a specific example please.

**Comment by MNSmith** [comment]
Same problem as me with column selections not being saved.  See #681

**Comment by kitenetter** [comment]
@johnvanbreda I thought the settings were being saved at one point, but certainly for the last four or five days they haven't. My current practice is to remove some of the fields I don't need (record ID and VC number for instance), add the ones I do need (taxon family and life stage) and then move the media column into the first column so that it is next to the tick boxes. For the last four or five days I've had to set that up afresh every time I go back in to iRecord.

**Comment by johnvanbreda** [comment]
I've fixed the columns save issue. Still need to cover the following:

> The recently added Redet button works, but the taxon displayed in the grid for the redetermined record is not immediately refreshed, and thus at first glance it appears the redet has not worked (although the comments tab does update immediately to show that it does work).
Are we able to force an immediate refresh in the grid following a redet? If not we will need to explain the delay clearly in our documentation (and perhaps add a Help button somewhere near the redet button).

> If I set my grid filter to show "all records", and I then verify a previously unverified record, that record gets taken out of the grid. Ideally it should remain visible since the filter should be including all records.

**Comment by DavidHepper** [comment]
Re. the issue with the icon for 'Correct', mine still shows a bad icon after various refreshes and browser cache clearances:
![image](https://user-images.githubusercontent.com/24915271/67270507-b8998100-f4b0-11e9-8978-78e07919874d.png)
(Image also shows the mouseover pop-up. This is the only record status icon that is bad.)

**Comment by DavidHepper** [comment]
Re. the issue with the icon for 'Correct', display of this icon is fixed at the top of the grid and in the Status field of the Details pane but not in the row of icons beneath the map:
![image](https://user-images.githubusercontent.com/24915271/68070905-6851d700-fd6c-11e9-96df-6ee5121d886d.png)

**Comment by johnvanbreda** [comment]
Icon fixed in develop branch of code - thanks @DavidHepper.

**Comment by johnvanbreda** [comment]
> If I set my grid filter to show "all records", and I then verify a previously unverified record, that record gets taken out of the grid. Ideally it should remain visible since the filter should be including all records.

- regarding this point, the existing verification page also does the same. Basically, it assumes that after you've made a decision on a record it assumes you want to move on to the next, no matter what the current filter is. The difficulty with changing this is that we can't easily work out if the record matches the current filter without running an extra query (due to all the filter combinations possible), therefore I'm not sure this is worth the extra overhead?

**Comment by kitenetter** [comment]
@johnvanbreda I agree that this is not worth the extra overhead.
