### ISSUE TITLE
Duplicated verification filters

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#783]
At one point, an edit to a filter was causing it to be duplicated in the lists:

![image](https://user-images.githubusercontent.com/16039111/73476478-37446b00-438a-11ea-91d9-c08981fb59b3.png)

I don't think that duplicates are still being created.

I think that last time I tried to delete one of the duplicates, it resulted in both copies getting removed. I haven't tested this again because I don't want to have to keep replacing filters that have vanished.

Raising as an issue to ask John about at our next meeting.

**Comment by kitenetter** [comment]
@johnvanbreda to deduplicate filters table

**Comment by johnvanbreda** [comment]
Done. Here's the query for safekeeping:
```sql
update filters_users fu
set deleted=true
from tofix tf
join filters_users fu2 on fu2.filter_id=tf.filter_id and fu2.user_id=tf.user_id and fu2.deleted=false
where fu.deleted=false
and fu.filter_id=tf.filter_id 
and fu.user_id=tf.user_id
and fu2.id<fu.id
```

**Comment by kitenetter** [comment]
@johnvanbreda I'm still seeing quite a lot of duplicates in the table here:
https://www.brc.ac.uk/irecord/filters/admin-list

I just edited the query "NBN - MBA territorial waters" here:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=6368

and it has caused similar edits to appear here:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=6370

**Comment by johnvanbreda** [comment]
@kitenetter these duplicates are duplications in the filters table, rather than just duplicate joins to the user in the filters_users table as I'd explained over the phone. I've just tried editing and resaving the filters_user_id=6368 record both in Safari (Mac) and Firefox (Windows) with no problems. Can you try again please, but send me the HAR file generated at the point in time when you see the popup message saying the filter has been saved. Thanks.

**Comment by kitenetter** [comment]
Test and check IDs

**Comment by kitenetter** [comment]
Example of duplicated filter is:
Diptera: Stratiomyidae; Harvey, Martin C.

Display at https://www.brc.ac.uk/irecord/filters/admin-list shown here:

![image](https://user-images.githubusercontent.com/16039111/78552448-6ef2e780-77ff-11ea-8c38-12de65aa1e84.png)

Filter IDs are:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=5984
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=6021

Edited name of 6021 to:
DUP Diptera: Stratiomyidae; Harvey, Martin C.

Both filters get renamed:

![image](https://user-images.githubusercontent.com/16039111/78552476-7a461300-77ff-11ea-8011-752b92e76f6d.png)

I did that by opening the edit page into a new tab, and as always I forgot that the Network panel that allows the HAR download only works on a single tab at a time. So I repeated a renaming process for these duplicated filters:
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=5983
https://www.brc.ac.uk/irecord/filters/admin-edit?filters_user_id=105

Edited name of 5983, both filters got renamed. HAR file:

[www.brc.ac.uk_Archive [20-04-06 12-07-23].zip](https://github.com/BiologicalRecordsCentre/iRecord/files/4437931/www.brc.ac.uk_Archive.20-04-06.12-07-23.zip)

**Comment by johnvanbreda** [comment]
Now fixed in the code, plus I ran the following to clean up existing data:
```sql
update filters_users set deleted=true where id in (
select fu.id
from filters_users fu
join filters_users fu2 on fu2.id<fu.id and fu2.user_id=fu.user_id and fu2.filter_id=fu.filter_id
where fu2.deleted=false and fu.deleted=false
)
```
