### ISSUE TITLE
Unintended consequence of photo licensing

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/iRecord#907]
I have just been trying to ensure that a user account is "Active" rather than "Blocked", but I cannot save their profile without ticking the "over 13" box and choosing a photo licence, both of which are mandatory. I can make an assumption that people who email us are over 13 (although strictly speaking I shouldn't do so), but I cannot choose a photo licence on behalf of someone else.

This is going to make it difficult for us to resolve the fairly frequent enquiries that we get from people who are unable to log in or unable to change their password.

I can't see any obvious solution to this unless there is any way of setting parts of the profile to be non-mandatory for admins.

The only other solution I can think of is to add a "not yet chosen" option to the licence list, but then we'd have to have a way of continuing to notify the user that their licence choice still needs to be made.

**Comment by kitenetter** [comment]
Marking as urgent because otherwise we have no way of responding to users who have login problems.

**Comment by kitenetter** [comment]
It's possible (but I'm not sure) that the issue with photo licences does not apply when I am logged in with full admin permissions, but is does apply when logged in with "user support" permissions. "User support" is a role I created recently to allow Siobhan Edney to assist with the iRecord inbox. She is able to see the People table and to edit user accounts, but this is when the photo licence problem arose.

The "under 13" issue is applicable at all times, whether logged in as admin or as user support.

**Comment by japonicus** [comment]
I think this is also an issue for end users. I needed to reset my iRecord password last week having forgotten it, a process that directed me to the general user profile page to enter a new password.

To set a new password I needed to declare that I was over 13 and also choose a license option. Age validation is not really a problem but the license choice requirement seemed inappropriate in that context (it irritated me at the time - even though I'm thoroughly in favour of open licensing and also understand the technical reasons for the license question).

Given that I was there to change a password rather than to make a considered choice about image licensing I think that the default flow should either have not asked about licensing at all or allowed that step to be skipped.

**Comment by burkmarr** [comment]
@kitenetter - as far as I can tell, the issue for photo licences _does_ apply, even when logged in as admin. I can't see a way in Drupal of allowing admins to override the required field status on account settings pages.

For the photo licensing I think there are two options:

1. Your suggestion of adding an 'unchosen' license option. We could do this through configuration without a code change. But once this option is selected by an administrator, the user won't see the 'You have not yet specified a media license...' message on log in. (That could be changed with a code change to the license module).

2. Make the field non-mandatory, but I think that requires a small code-change to the licence module - there's no way to configure it through the Drupal configuration. The downside is that new users could selecting this option when registering.

For the over 13 field I think that we would need to make this non-mandatory which we can do through normal Drupal configuration. But that would mean that users could register on the site without checking the box. 

I looked at this module - https://www.drupal.org/project/field_permissions - because I thought it might enable us remove the under 13 field from users account settings being edited by admin users. It was already installed (but disabled) on develop, so I enabled it and configured the under 13 field, aiming to hide the field from admins (hoping that would make the form savable without setting a value), but it still appears on a profile page being edited by admin.

![image](https://user-images.githubusercontent.com/9275178/90384196-1965fb80-e079-11ea-8502-6c11ff43a977.png)

@BirenRathod - do you have any experience of this module or any other suggestions on this issue?

**Comment by BirenRathod** [comment]
@burkmarr field_permission module is not for hiding any fields.

**Comment by BirenRathod** [comment]
@burkmarr 
I checked the field settings of "under 13". One perticular thing I noticed is that it has got below settings enabled. 
![image](https://user-images.githubusercontent.com/5941255/90386747-eb82b600-e07c-11ea-85d9-315a4a3bfa6a.png)
In that case you can't make it invisible on user registration page.

**Comment by BirenRathod** [comment]
Same on their editing page.

**Comment by burkmarr** [comment]
@BirenRathod - we wanted to remove it from the admin's view of a user's account settings - not the user's view. But it could be that you can't do it for a required field in that case either.

**Comment by BirenRathod** [comment]
@burkmarr That's correct. you can't do it for admin's view too.

**Comment by johnvanbreda** [comment]
I don't think field_permissions would hide it from admin view, because true admins always have permissions to everything (effectively permissions checks get disabled). 

What about:
1. Code change in the module to make it non-mandatory.
2. Code change in the module to use form hooks to make it mandatory on the registrations page only.

**Comment by burkmarr** [comment]
@johnvanbreda - I think that is a good way to go. Shall I have a look at this first? I'm not very familiar with Drupal programming, but I'm happy to look and consult you if I can't work anything out.

We still have the under 13 problem, but we could make that non-mandatory for a while until we find a solution for it.

**Comment by johnvanbreda** [comment]
I think unless @DavidRoy allocates it to me it's over to you @burkmarr. You might want to do something like this in the .module file:
```php
function mymodule_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id === 'user_register_form') {
    // Change $form to make appropriate field mandatory
  }
```
Replace mymodule with the module name.

As to how to change the field, you need to work out the right field name. Some clues at https://stackoverflow.com/questions/12626086/drupal-7-make-field-required-in-form-user-profile-form-alter.

**Comment by DavidRoy** [comment]
@burkmarr could you pick this one up, thanks

**Comment by burkmarr** [comment]
@johnvanbreda - I was maybe confused about what field we were talking about before. I've had a look and can see the change to make the licensing selection mandatory only on registration form is very straightforward to make in iForm licensing sub-module. 

Were you suggesting that I do similar for the under 13 field in iForm module? I hestitate because it's not an Indicia field but specific to iRecord.

**Comment by burkmarr** [comment]
@kitenetter - the live site is now using the latest release which addresses tht media-license module so both these issues are now fixed. In summary media license selection and over 13 field are both mandatory on registration, but not on editing existing profile.

**Comment by kitenetter** [comment]
Many thanks @burkmarr that sounds like a good solution. Do existing users still see the message prompting them to set a photo licence if they haven't yet done so?

**Comment by burkmarr** [comment]
@kitenetter - yes; you can see how that looks by masquerading as another user (you can pick one at random since most haven't yet made a selection).

**Comment by kitenetter** [comment]
Excellent - closing.
